export const API_URL_CONFIG = {
  LAST_DATE_API: import.meta.env.VITE_LAST_DATE_API,
  REQUIRE_MONTHLY_API: import.meta.env.VITE_REQUIRE_MONTHLY_API,
  DISTRIBUTOR_API: import.meta.env.VITE_DISTRIBUTOR_API,
  INV_REPORT_API: import.meta.env.VITE_INV_REPORT_API,
  DIST_WAREHOUSEWISE_SALES_API: import.meta.env
    .VITE_DIST_WAREHOUSEWISE_SALES_API,
  DISTWISE_ANNUAL_SALES_API: import.meta.env.VITE_DISTWISE_ANNUAL_SALES_API,
  DISTWISE_MONTHLY_SALES_API: import.meta.env.VITE_DISTWISE_MONTHLY_SALES_API,
} as const;
